title: Vikram Kumar | Managing Director | BlackRock
description: Managing Director - Aladdin Wealth Tech | BlackRock | 20+ years in Technology Leadership | FMS MBA
author: Vikram Kumar
email: vikram17june@gmail.com
phone: +91-9810175951
location: NCR, India
url: https://coolviki.github.io
baseurl: ""

# Custom Apple-inspired theme (no external theme)
# Using custom layouts and CSS

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SASS configuration for custom styling
sass:
  style: compressed

# Social links
social:
  name: Vikram Kumar
  links:
    - https://www.linkedin.com/in/vikramkumar
    - https://github.com/coolviki

# SEO settings
lang: en
timezone: Asia/Kolkata

# Google Analytics
google_analytics: G-5E0NPRC1M7