theme: jekyll-theme-minimal
title: Vikram Kumar - Professional Profile
description: Managing Director, Head of Aladdin Wealth Tech - India at BlackRock | FMS MBA
author: Vikram Kumar
url: https://coolviki.github.io
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

social:
  name: Vikram Kumar
  links:
    - https://www.linkedin.com/in/vikramkumar
    - https://github.com/coolviki